### ISSUE TITLE
While scrolling or use the up/down arrows on the keyboard, the amount changes

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/beam-bridge-app#14]
When the cursor is on the "Amount" active field on the send screen, and you are scrolling or tap up/down arrows on the keyboard, the amount changes.
**Steps to reproduce:**
1. Launch the Bridges DApp from My DApp Store.
2. Press the "BEAM TO ETHEREUM" button.
3. Paste the copied ETHEREUM BRIDGE address.
4. Tap on the "Amount" active field and scroll or use up/down arrows on your keyboard.
**Expected result:** the amount doesn't change.
**Actual result:** the amount changes.
![2022-08-26_12-41-07](https://user-images.githubusercontent.com/83376495/186876553-2bec4ad3-ac05-4358-a4fd-38c00d53f76c.gif)
The same situation is also on the https://bridges-dappnet.web.app/send
![2022-08-26_12-43-37](https://user-images.githubusercontent.com/83376495/186876785-fc51325d-e976-455d-90db-9286925f6c28.gif)

**Comment by Denis-Asipenko** [comment]
checked
