### ISSUE TITLE
Add the 'Copied to clipboard' popup

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/beam-bridge-app#19]
While pressing the 'copy' button, add the 'Copied to clipboard' popup
![2022-08-26_16-00-42](https://user-images.githubusercontent.com/83376495/186909158-2b26f050-b04c-4440-a649-e491e0ac2b67.gif)
![2022-08-26_16-02-25](https://user-images.githubusercontent.com/83376495/186909499-1520e3cb-7bf5-462a-91a2-b37cc9d2f700.gif)

**Comment by Denis-Asipenko** [comment]
checked
