### ISSUE TITLE
Bridges. Main screen 

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-bridge-app#2]
**Main screen before any action took place**
https://zpl.io/bWyzd3n
1. Add caption below send/receive buttons
<img width="699" alt="Screenshot at Dec 14 22-02-05" src="https://user-images.githubusercontent.com/7249484/146012960-f67f8bf3-c0ae-40a2-b2f6-490f1dc27706.png">

2. Rename Send/receive buttons into Beam to Ethereum/Ethereum to Beam 
<img width="692" alt="Screenshot at Dec 14 22-02-17" src="https://user-images.githubusercontent.com/7249484/146013011-9e8bfaf9-bf76-47e4-b845-758ac9b7cc8f.png">

**Main screen with empty transactions list (after user opened send or receive screens)**
https://zpl.io/aXRnOEx
![bridges main empty](https://user-images.githubusercontent.com/7249484/146014536-b4c306e5-175a-42e5-bedf-7d83a123a544.png)

**Main screen with transactions**
https://zpl.io/VYz9gDE
1. Add "incoming funds" list. After the user taps the "confirm" button, the offer should disappear from the list.
<img width="680" alt="Screenshot at Dec 07 17-31-17" src="https://user-images.githubusercontent.com/7249484/145003521-f5a2d964-016e-4cdc-9726-11fafe3dff19.png">

2. If there's more than 1 incoming offer, show the "confirm all" button in the header of the table
https://zpl.io/V0zQXWR
<img width="675" alt="Screenshot at Dec 07 17-31-37" src="https://user-images.githubusercontent.com/7249484/145003531-2fca9653-7d0c-46cf-bb5b-bc03dd994e06.png">

3. Add USD value column and rework "status" column
<img width="730" alt="Screenshot at Dec 07 17-32-03" src="https://user-images.githubusercontent.com/7249484/145003591-cb21ec55-edbf-43bb-909b-326595866a6b.png">

**Receive confirmation screen** 
https://zpl.io/blewKDz
![bridges receive confirmation](https://user-images.githubusercontent.com/7249484/145008491-bc2c5554-cef0-44e9-9f88-ceb4bfb3ccf0.png)

If confirmation includes more than one transaction, add that info int the dialog.
<img width="528" alt="Screenshot at Dec 07 18-03-11" src="https://user-images.githubusercontent.com/7249484/145008542-3053b071-71ad-447a-ad61-2ac25fa31442.png">

**Comment by beam-mw** [comment]
Older design. Irrelevant
