### ISSUE TITLE
Add the link for downloading beam wallet

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/beam-bridge-app#20]
Add the [link ](https://beam.mw/downloads/)for downloading beam wallet to the "Beam Wallet" hyperlink on the ETH to BEAM/ BEAM to ETH screens.

![2022-08-26_16-58-18](https://user-images.githubusercontent.com/83376495/186923081-f441889c-95f3-4a10-94df-d3d754e528a4.gif)
![2022-08-26_16-33-52](https://user-images.githubusercontent.com/83376495/186923111-3f71c3b9-3147-40b0-b4e7-70c0b4419a4e.gif)

**Comment by Denis-Asipenko** [comment]
checked
