### ISSUE TITLE
Eth to bridge wallet menu

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-bridge-app#21]
https://www.figma.com/file/LteN0e1tygpYgzjQmCPZCu/Bridges-Landing?node-id=260%3A2865
<img width="690" alt="Снимок экрана 2022-09-12 в 13 25 23" src="https://user-images.githubusercontent.com/94360080/189631442-114c0428-e93c-4184-a045-ee34644c0057.png">

https://www.figma.com/file/LteN0e1tygpYgzjQmCPZCu/Bridges-Landing?node-id=260%3A2561
<img width="685" alt="Снимок экрана 2022-09-12 в 13 25 49" src="https://user-images.githubusercontent.com/94360080/189631514-6d4334c1-2e80-416a-8bb0-3d3d0ed329b7.png">

**Comment by Denis-Asipenko** [comment]
checked
