### ISSUE TITLE
Bridges. Receive screen 

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-bridge-app#4]
1. Receive screen
https://zpl.io/bey0Lzm
![bridges receive](https://user-images.githubusercontent.com/7249484/145008007-8bdf6045-435c-49e5-a47c-a878ed1cba59.png)

- add "receive" blue gradient
- rename screen into Ethereum to Beam 
<img width="676" alt="Screenshot at Dec 07 18-03-51" src="https://user-images.githubusercontent.com/7249484/145008696-c4c0c389-f081-491a-aa69-01ec8f31fd8e.png">

- add Proceed icon (should open ethereum side of the wallet, send screen with autofilled address https://zpl.io/2jynYKO)
<img width="423" alt="Screenshot at Dec 07 18-04-06" src="https://user-images.githubusercontent.com/7249484/145008712-d707f900-93b5-4704-b16a-5a9563e360e1.png">

- Add currency dropdown. By default should be selected ETH. After user changes the currency, the address should be updated automatically.
https://zpl.io/293Mk7z
![bridges receive dropdown](https://user-images.githubusercontent.com/7249484/145008563-11f4c3f3-03e4-48a4-a0fb-443818694ab2.png)

**Comment by beam-mw** [comment]
Old design. Irrelevant
