### ISSUE TITLE
Bridges. Main screen relay info

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-bridge-app#5]
https://zpl.io/bWyzd3n
Add Total transfered amount (to BEAM/ to ethereum) and Letest/next transfer sections
<img width="639" alt="Screenshot at Dec 08 13-38-29" src="https://user-images.githubusercontent.com/7249484/145154547-7ac82175-d649-4015-86ec-f792ca95cba3.png">

The height of all 3 sections should be same and depends on sections, that has maximum amount of lines.
<img width="592" alt="Screenshot at Dec 08 13-38-46" src="https://user-images.githubusercontent.com/7249484/145154586-b683f31d-27f0-4742-8415-b98657131f90.png">

**Comment by beam-mw** [comment]
Older design. Irrelevant
