### ISSUE TITLE
Bridges. Bridge receive page changes

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-bridge-app#6]
1. Make central area location symmetrical from the sides. 
2. text changes:

- p1 change to the green button "Ethereum side of the bridge"
- p2 delete
- p3 change to the grey button "Manual way to the bridge" - click on the button opens p3 instruction .

https://www.figma.com/file/LteN0e1tygpYgzjQmCPZCu/Bridges-Landing?node-id=57%3A4584
<img width="701" alt="Снимок экрана 2022-07-29 в 14 34 57" src="https://user-images.githubusercontent.com/94360080/181750624-88fa8f42-cd9b-4bc2-ad75-5692c5060d77.png">

**Comment by VikMaevskaya** [comment]
add icon before the Link "Ethereum side of the bridge"
font size bigger,I think, like bUSD size.
<img width="158" alt="Снимок экрана 2022-08-08 в 10 35 18" src="https://user-images.githubusercontent.com/94360080/183364540-d5b8e91e-115d-403f-ab96-b0d373314f55.png">

p2 delete
p3 change to the grey dropdown trxt button "Manual way to the bridge" - click on the button opens p3 instruction .

<img width="275" alt="Снимок экрана 2022-08-08 в 10 44 58" src="https://user-images.githubusercontent.com/94360080/183366210-1947ff43-d42d-42d5-b0c5-1a43729add0b.png">

**Comment by dariatarakanova** [comment]
Open view for Manual way - https://www.figma.com/file/LteN0e1tygpYgzjQmCPZCu/Bridges-Landing?node-id=260%3A2561
Hidden view - https://www.figma.com/file/LteN0e1tygpYgzjQmCPZCu/Bridges-Landing?node-id=260%3A2865
