### ISSUE TITLE
Add the address validation on the BEAM to ETH send screen

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/beam-bridge-app#9]
- [ ] While sending a token from BEAM wallet to ETH there is no address validation, so a user can send an amount to a random character set.

![2022-08-25_17-39-39](https://user-images.githubusercontent.com/83376495/186695118-1584e3db-0062-42aa-9f8c-efc43091ec77.gif)

- [ ] It is also necessary to prohibit entering special characters in the address field.

<img width="1364" alt="2022-08-26_14-19-18" src="https://user-images.githubusercontent.com/45556620/186895706-ef210f4d-e971-4fb9-82d0-7f2867e93470.png">
<img width="1024" alt="2022-08-26_14-20-34" src="https://user-images.githubusercontent.com/45556620/186896142-54988feb-5dfd-49ef-a2d0-d7b6f8cae399.png">

- [ ] Prohibit entering a Cyrillic symbols into the address field.

![image](https://user-images.githubusercontent.com/83376495/186901833-1b415df6-769f-42c7-a962-76140eff8dc7.png)

![image](https://user-images.githubusercontent.com/83376495/186901865-c226a92c-40f5-41ac-aec7-0673cc65e829.png)

**Comment by kovaletskaterina** [comment]
Prohibit to enter a Cyrillic symbols into the address field
![image](https://user-images.githubusercontent.com/83376495/186895535-13151d6e-b031-4669-bff9-7c4e033feb7b.png)
![image](https://user-images.githubusercontent.com/83376495/186895547-c157e7b0-ea2d-4340-be4b-4cf77debfa17.png)

**Comment by Denis-Asipenko** [comment]
checked
